app = "sinyalbtc-webhook"
primary_region = "sin"

[build]
  image = "python:3.11-slim"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
